import pygame, sys, math, random, inspect

class Prices():
   
    def __init__(self):
        prices = {"blackCat": 3,
                  "calicoCat": 1,
                  "owl": 2,
                  "frog": 5,
                  "raccoon": 5,
                  "spell": [1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1],
                  "speed": 1,
                  "health": 2,
                  "fullHeal": 3,
                  "halfHeal": 1,
                  "revive": 10,
                  "eyes": [1,
                           1,
                           1,
                           1,
                           1,
                           1,
                           1],
                  "mouths": [1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1],
                  "colors": [1,
                             1,
                             1,
                             1],
                  "hats": [1,
                           1,
                           1],
                  "shirts": [1,
                             1,
                             1],
                  "glasses": [1,
                              1,
                              1,
                              1]}
